name: Deploy to Render

on:
  push:
    branches:
      - feature

  pull_request:
    branches:
      - feature

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}

        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"serviceId": "srv-cvqhqm7gi27c73elh760"}' \
            https://api.render.com/v1/services/srv-cvqhqm7gi27c73elh760/deploys
